id: P003317
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W19848
  title: ལཱ་མོ་གྲགས་པ་རྒྱ་མཚོའི་སྐུ་ཕྲེང་རིམ་བྱོན་གྱི་རྣམ་ཐར།
  author: ''
  volumes:
    414b3fd5c51642e5bdc68e3215f8a24e:
      image_group_id: I1KG14829
      title: ''
      volume_number: 1
      total_pages: 150
      base_file: v001.txt
